# Generated by Django 5.1 on 2024-10-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "USER"),
                            ("ADMIN", "ADMIN"),
                            ("GEST", "GEST"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User1",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=10)),
                (
                    "email",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conferenceApp.role",
                    ),
                ),
            ],
        ),
    ]
