# Generated by Django 5.1 on 2024-11-01 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0002_alter_role_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user1",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="conferenceApp.role"
            ),
        ),
    ]
