# Generated by Django 5.1 on 2024-11-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0003_alter_user1_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("heureDebut", models.TimeField()),
                ("heureFine", models.TimeField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nom", models.CharField(max_length=100)),
                ("lieu", models.CharField(max_length=100)),
                ("them", models.TextField()),
                ("dateDebut", models.DateField()),
                ("dateFin", models.DateField()),
                ("user", models.ManyToManyField(to="conferenceApp.user1")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conferenceApp.session",
                    ),
                ),
            ],
        ),
    ]
