# Generated by Django 5.1 on 2024-11-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0004_session_conference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conference",
            name="session",
        ),
        migrations.AddField(
            model_name="session",
            name="conference",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="conferenceApp.conference",
            ),
            preserve_default=False,
        ),
    ]
