# Generated by Django 5.1 on 2024-11-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0006_rename_heurefine_session_heurefin"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="intervenant",
            field=models.ManyToManyField(to="conferenceApp.user1"),
        ),
        migrations.AddField(
            model_name="user1",
            name="estIntervenant",
            field=models.BooleanField(default=False),
        ),
    ]
