# Generated by Django 5.1 on 2024-11-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0007_session_intervenant_user1_estintervenant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="intervenant",
        ),
        migrations.AddField(
            model_name="session",
            name="intervenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="conferenceApp.user1",
            ),
            preserve_default=False,
        ),
    ]
