# Generated by Django 5.1 on 2024-11-02 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conferenceApp",
            "0009_remove_session_intervenant_session_intervenants_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user1",
            name="role",
            field=models.ForeignKey(
                default="USER",
                on_delete=django.db.models.deletion.CASCADE,
                to="conferenceApp.role",
            ),
        ),
    ]
