# Generated by Django 5.1 on 2024-11-02 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0010_alter_user1_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("USER", "USER"), ("ADMIN", "ADMIN"), ("GEST", "GEST")],
                default="USER",
                max_length=5,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user1",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="conferenceApp.role"
            ),
        ),
    ]
