# Generated by Django 5.1 on 2024-11-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0011_alter_role_role_alter_user1_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user1",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user1",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
