# Generated by Django 5.1 on 2024-11-02 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferenceApp", "0013_alter_user1_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="intervenants",
        ),
        migrations.CreateModel(
            name="SessionIntervenant",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "intervenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conferenceApp.user1",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conferenceApp.session",
                    ),
                ),
            ],
        ),
    ]
